// <auto-generated />
using System;
using ComplaintManagementSystem.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ComplaintManagementSystem.Migrations
{
    [DbContext(typeof(ComplaintManagementSystemContext))]
    [Migration("20260602093831_ChangedSomeComplaintPropertiesToNullable")]
    partial class ChangedSomeComplaintPropertiesToNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ComplaintManagementSystem.Models.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommentId"));

                    b.Property<int>("ComplaintId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CommentId");

                    b.HasIndex("ComplaintId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.Complaint", b =>
                {
                    b.Property<int>("ComplaintId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComplaintId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComplaintCategoryCategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComplaintPriorityPriorityId")
                        .HasColumnType("integer");

                    b.Property<int?>("ComplaintStatusStatusId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int?>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("ComplaintId");

                    b.HasIndex("ComplaintCategoryCategoryId");

                    b.HasIndex("ComplaintPriorityPriorityId");

                    b.HasIndex("ComplaintStatusStatusId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("UserId");

                    b.ToTable("Complaints");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.ComplaintAttachment", b =>
                {
                    b.Property<int>("AttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AttachmentId"));

                    b.Property<int>("ComplaintId")
                        .HasColumnType("integer");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AttachmentId");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintAttachments");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.ComplaintCategory", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Categoryname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CategoryId");

                    b.ToTable("ComplaintCategories");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.ComplaintHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryId"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ChangedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ComplaintId")
                        .HasColumnType("integer");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("HistoryId");

                    b.HasIndex("ComplaintId");

                    b.ToTable("ComplaintHistories");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.ComplaintPriority", b =>
                {
                    b.Property<int>("PriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PriorityId"));

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("PriorityId");

                    b.ToTable("ComplaintPriorities");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.ComplaintStatus", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("StatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("StatusId");

                    b.ToTable("ComplaintStatuses");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("DepartmentId")
                        .HasColumnType("integer");

                    b.Property<string>("EmployeeMail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.EscalatedComplaint", b =>
                {
                    b.Property<int>("EscalatedId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EscalatedId"));

                    b.Property<int>("ComplaintId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EscalatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EscalatedLevelId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EscalatedId");

                    b.HasIndex("ComplaintId");

                    b.HasIndex("EscalatedLevelId");

                    b.ToTable("EscalatedComplaints");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.EscalatedLevel", b =>
                {
                    b.Property<int>("EscalatedLevelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EscalatedLevelId"));

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("EscalatedLevelId");

                    b.ToTable("EscalatedLevels");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.SLA", b =>
                {
                    b.Property<int>("SlaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SlaId"));

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<int>("ResolutionHours")
                        .HasColumnType("integer");

                    b.HasKey("SlaId");

                    b.HasIndex("PriorityId")
                        .IsUnique();

                    b.ToTable("SLAs");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("JoinedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.Comment", b =>
                {
                    b.HasOne("ComplaintManagementSystem.Models.Complaint", "Complaint")
                        .WithMany("Comments")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.Complaint", b =>
                {
                    b.HasOne("ComplaintManagementSystem.Models.ComplaintCategory", "ComplaintCategory")
                        .WithMany("Complaints")
                        .HasForeignKey("ComplaintCategoryCategoryId");

                    b.HasOne("ComplaintManagementSystem.Models.ComplaintPriority", "ComplaintPriority")
                        .WithMany("Complaints")
                        .HasForeignKey("ComplaintPriorityPriorityId");

                    b.HasOne("ComplaintManagementSystem.Models.ComplaintStatus", "ComplaintStatus")
                        .WithMany("Complaints")
                        .HasForeignKey("ComplaintStatusStatusId");

                    b.HasOne("ComplaintManagementSystem.Models.Employee", "Employee")
                        .WithMany("Complaints")
                        .HasForeignKey("EmployeeId");

                    b.HasOne("ComplaintManagementSystem.Models.User", "User")
                        .WithMany("Complaints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplaintCategory");

                    b.Navigation("ComplaintPriority");

                    b.Navigation("ComplaintStatus");

                    b.Navigation("Employee");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.ComplaintAttachment", b =>
                {
                    b.HasOne("ComplaintManagementSystem.Models.Complaint", "Complaint")
                        .WithMany("ComplaintAttachments")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.ComplaintHistory", b =>
                {
                    b.HasOne("ComplaintManagementSystem.Models.Complaint", "Complaint")
                        .WithMany("ComplaintHistories")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.Employee", b =>
                {
                    b.HasOne("ComplaintManagementSystem.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComplaintManagementSystem.Models.User", "User")
                        .WithOne("Employee")
                        .HasForeignKey("ComplaintManagementSystem.Models.Employee", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.EscalatedComplaint", b =>
                {
                    b.HasOne("ComplaintManagementSystem.Models.Complaint", "Complaint")
                        .WithMany("EscalatedComplaints")
                        .HasForeignKey("ComplaintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ComplaintManagementSystem.Models.EscalatedLevel", "EscalatedLevel")
                        .WithMany("EscalatedComplaints")
                        .HasForeignKey("EscalatedLevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Complaint");

                    b.Navigation("EscalatedLevel");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.SLA", b =>
                {
                    b.HasOne("ComplaintManagementSystem.Models.ComplaintPriority", "ComplaintPriority")
                        .WithOne("SLA")
                        .HasForeignKey("ComplaintManagementSystem.Models.SLA", "PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ComplaintPriority");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.Complaint", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("ComplaintAttachments");

                    b.Navigation("ComplaintHistories");

                    b.Navigation("EscalatedComplaints");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.ComplaintCategory", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.ComplaintPriority", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("SLA");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.ComplaintStatus", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.Employee", b =>
                {
                    b.Navigation("Complaints");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.EscalatedLevel", b =>
                {
                    b.Navigation("EscalatedComplaints");
                });

            modelBuilder.Entity("ComplaintManagementSystem.Models.User", b =>
                {
                    b.Navigation("Complaints");

                    b.Navigation("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
